# Flow colorscheme | Alacritty
# https://github.com/0xstepit/flow.nvim

# Black and white
[colors.primary]
background = '#1f282e'
foreground = '#94aab8'

# Normal colors
[colors.normal]
black = '#0d0d0d'
red = '#862d34'
green = '#34862d'
yellow = '#86862d'
blue = '#2d6186'
magenta = '#592d86'
cyan = '#2d8670'
white = '#f2f2f2'

# Bright colors
[colors.bright]
black = '#0d0d0d'
red = '#862d34'
green = '#34862d'
yellow = '#86862d'
blue = '#2d6186'
magenta = '#592d86'
cyan = '#2d8670'
white = '#f2f2f2'

# Search colors
[colors.search.matches]
foreground = '#fbff00'
background = '#0d0d0d'

[colors.search.focused_match]
foreground = '#0d0d0d'
background = '#fbff00'

# Selection colors
[colors.selection]
background = '#fbff00'
text = '#0d0d0d'

# Cursors
# If you don't want to override original behavior, which is nice,
# remove [colors.cursor] and [colors.vi_mode_cursor].
[colors.cursor]
cursor = '#fbff00'
text = '#0d0d0d'

[colors.vi_mode_cursor]
cursor = '#fbff00'
text = '#0d0d0d'

[colors.footer_bar]
foreground = '#fbff00'
background = '#0d0d0d'

# Purple color
[[colors.indexed_colors]]
index = 93
color = '#592d86'

# Fluo Colors
[[colors.indexed_colors]]
index = 198
color = '#fbff00'
